### ISSUE TITLE
Doesn't run local server

### ISSUE THREAD

**Issue by tarim** [bradwestfall/CSS-Tricks-React-Series#1]
Hi,

I try to run your app Guide-3 on my local server, and it doesn't work at all. Any idea?

Thanks,

**Comment by bodiddlie** [comment]
I'm running on windows and ran into this as well. Windows paths strike again! On the `serve:node` and `serve:api` tasks in the gulpfile I just did a lazy __dirname + to the exec calls. Would probably be best to do a `path.join` on them, but this was a quick fix so I could run it.

**Comment by alex-shamshurin** [comment]
+1

I got this on windows:

```
10:49:23] Starting 'serve:api'...
[10:49:24] 'serve:api' errored after 7 ms
[10:49:24] Error: 1
    at formatError (C:\Users\salex\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\salex\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:90:13)
    at Gulp.emit (events.js:182:7)
    at Gulp.Orchestrator._emitTaskDone (C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\index.js:264:8)
    at C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\index.js:275:23
    at finish (C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\lib\runTask.js:21:8)
    at ChildProcess.cb (C:\Users\salex\workspace\CSS-Tricks-React-Series\guide-3-redux\node_modules\orchestrator\lib\runTask.js:29:3)
    at emitTwo (events.js:105:20)
    at ChildProcess.emit (events.js:185:7)
```

**Comment by bradwestfall** [comment]
@tarim Are you on Windows? along with @bodiddlie and @salex772

**Comment by bradwestfall** [comment]
@bodiddlie Can you do a PR with `__dirname` and also with `path.join` once you've got it working on Windows? I just cant test Windows, but if it works on my Mac and you say it works on Windows we can get it merged

**Comment by bodiddlie** [comment]
Okay submitted a PR. I'm at work so I can't test on my Mac, but I think it should be good.
