### ISSUE TITLE
Can't start gulp

### ISSUE THREAD

**Issue by nchery** [bradwestfall/CSS-Tricks-React-Series#11]
Hi i'm getting the following issue when attempting to run gulp on a mac. I think i've installed all the necessary dependencies. any tips ? thk

[09:42:25] Using gulpfile ~/Desktop/Projects/CSS-Tricks-React-Series/guide-3-redux/gulpfile.js
[09:42:25] Starting 'serve:node'...
[09:42:25] Starting 'restore-database'...
[09:42:25] [nodemon] 1.10.0
[09:42:25] [nodemon] to restart at any time, enter `rs`
[09:42:25] [nodemon] watching: server.js
[09:42:25] [nodemon] starting `/Users/Nico/Desktop/Projects/CSS-Tricks-React-Series/guide-3-redux/node_modules/.bin/babel-node ./server.js`
sh: /Users/Nico/Desktop/Projects/CSS-Tricks-React-Series/guide-3-redux/node_modules/.bin/babel-node: No such file or directory
[09:42:25] [nodemon] failed to start process, "/Users/Nico/Desktop/Projects/CSS-Tricks-React-Series/guide-3-redux/node_modules/.bin/babel-node ./server.js" exec not found
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (127)
    at emit (events.js:144:17)
    at ChildProcess.<anonymous> (/Users/Nico/Desktop/Projects/CSS-Tricks-React-Series/guide-3-redux/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/run.js:116:11)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by bradwestfall** [comment]
Hi @nchery, I hate to ask such a basic question if you took care of it, but did you do the `npm install`? Remember, you'll need to do this from within each of the three guides -- since each guide serves as it's own project. Perhaps you did the `npm install` in the folder above?

**Comment by nchery** [comment]
@bradwestfall . Yes i did...looks like there is some issue with the dependency graceful-fs....here some interesting resources
https://github.com/sequelize/cli/issues/291 
&
http://stackoverflow.com/questions/37346512/how-to-fix-fs-re-evaluating-native-module-sources-is-not-supported-graceful

**Comment by nchery** [comment]
ok i reinstalled Gulp and it works now

**Comment by bradwestfall** [comment]
Cool, thanks @nchery
